# Generated by Django 3.1.2 on 2020-11-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['nombre'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
    ]
