# Generated by Django 3.1.2 on 2020-11-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Peso'),
        ),
    ]
