# Generated by Django 3.1.2 on 2020-11-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.BigIntegerField(default=1, verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
