# Generated by Django 3.1.2 on 2020-11-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='animal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.animal'),
        ),
    ]
