# Generated by Django 3.1.2 on 2020-11-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20201109_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='animal_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='animal_id',
            field=models.ManyToManyField(to='producto.Animal'),
        ),
    ]
