# Generated by Django 3.1.2 on 2020-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20201110_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoría Activada/No Activa')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='animal_id',
            field=models.ManyToManyField(to='producto.Animal'),
        ),
    ]
